config/routes.rb
Viverelajacion::Application.routes.draw do

  resources :productos
  resources :messages, :only => [:new, :create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tips

  get 'store',to: 'store#index'
  get 'equipo',to: 'equipo#index'

  get "service/index"
  get "service/kine"
  get "service/masaje"
  get "service/fisico"
  get "home/index"

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/base_model.rb
class BaseModel < ActiveRecord::Base
    self.abstract_class = true
    def self.by_creation
        self.order('created_at DESC')
    end
end

app/models/message.rb
class Message
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers
  # attribute :name
  # attribute :email
  # attribute :content

  attr_accessor :name, :email, :content, :nickname


  validates :email, :format => { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,8}\z/i , on: :create}
  validates :content, :presence => true
  validates :name, :presence => true
  validates :message,:length => { :minimum => 10, :maximum => 5000 }
  validates :nickname,
    :format => { :with => /^$/, :multiline => true },
    :presence => false

  def initialize(attributes = {})
    if not attributes.nil?
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end
  end

  def deliver
    # return false unless valid?
    #MailWorker.perform_async(self.email, self.name, self.content)
    Pony.mail(
     :from => self.email,
     :reply_to => self.email,
     :subject => "Contacto desde Viverelajacion.cl | #{self.name}",
     :body => self.content,
     :html_body => simple_format(self.content)
   )
  end

  def persisted?
    false
  end
end

app/models/producto.rb
class Producto < BaseModel
  has_attached_file :imagen, :styles => { :small => "240x240#", :large => "300x300#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :imagen, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :imagen

  after_create    :post_to_facebook

  def post_to_facebook
    if ENV['FACEBOOK_ACCESS_TOKEN'] and self.descuento > 0
        owner = FbGraph::User.me(ENV['FACEBOOK_ACCESS_TOKEN'])
        pages = owner.accounts
        page  = pages.detect {|page| page.identifier == ENV['FACEBOOK_PAGE_ID']}
        page.feed!(
            :message => "Nueva Promocion!! #{self.nombre}",
            :link => "http://www.viverelajacion.cl/store/",
            :name => "Nueva Promocion!! #{self.nombre}",
            :description => truncate(raw(self.descripcion),:length => 150,:omision => '...',:escape => false),
            :picture => self.imagen.url(:small)
        )
    end
  end

  def self.by_type(clase)
    self.where('clase = ?',clase)
  end


  def self.promociones
    where('descuento > 0').by_creation
  end
end

app/models/tip.rb
class Tip < BaseModel
    has_attached_file :portada,
        :styles => { :small => "200x200#", :large => "940" },
        :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :portada, :content_type => /\Aimage\/.*\Z/
    validates_attachment_presence :portada
    after_create    :post_to_facebook

    private
    def post_to_facebook
        if ENV['FACEBOOK_ACCESS_TOKEN']
            owner = FbGraph::User.me(ENV['FACEBOOK_ACCESS_TOKEN'])
            pages = owner.accounts
            page  = pages.detect {|page| page.identifier == ENV['FACEBOOK_PAGE_ID']}
            page.feed!(
                :message => self.titulo,
                :link => "http://www.viverelajacion.cl/tips/#{self.id}",
                :name => self.titulo,
                :description => truncate(raw(self.texto),:length => 150,:omision => '...',:escape => false),
                :picture => self.portada.url(:small)
            )
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/equipo_controller.rb
class EquipoController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @last_tip  = Tip.by_creation.first
    @productos = Producto.by_creation.last
    @tips      = Tip.by_creation.limit(4)
    @promociones = Producto.promociones.limit(4)
    @message   = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.deliver
      redirect_to root_url, notice: "Tu mensaje fue enviado, nos contactaremos contigo!"
    else
      render "home#index"
    end
  end

end

app/controllers/productos_controller.rb
class ProductosController < InheritedResources::Base
    def create
        @producto = Producto.create(user_params)
    end

    def index
        @productos = Producto.all
    end

    def show
    end
    private
    def user_params
        params.require(:producto).permit(:imagen)
    end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController

  def kine
  end

  def masaje
  end

  def fisico
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @productos_kinesiologia = Producto.by_type('kinesiologia')
    @productos_masaje = Producto.by_type('masaje')
    @productos_actividad = Producto.by_type('actividad')
  end
end

app/controllers/tips_controller.rb
require "html_truncator"
class TipsController < InheritedResources::Base
    def index
        @tips = Tip.by_creation.limit(20)
    end

    def show
        @tip = Tip.find(params[:id])
        @image = "http://#{request.host}:#{request.port}#{@tip.portada.url(:large)}"
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert-info"
    when :success then "alert-success"
    when :error then "alert-error"
    when :alert then "alert-error"
    else
      "alert-success"
    end
  end

  def html_truncate(html, truncate_length, options={})  
    text, result = [], []  
    # get all text (including punctuation) and tags and stick them in a hash  
    html.scan(/<\/?[^>]*>|[A-Za-z0-9.,\/&#;\!\+\(\)\-"'?]+/).each { |t| text << t }  
    text.each do |str|  
      if truncate_length > 0  
        if str =~ /<\/?[^>]*>/  
          previous_tag = str  
          result << str  
        else  
          result << str  
          truncate_length -= str.length  
        end  
      else  
        # now stick the next tag with a  that matches the previous   
        # open tag on the end of the result  
        if previous_tag && str =~ /<\/([#{previous_tag}]*)>/  
          result << str  
        end  
      end  
    end  
    return result.join(" ") + options[:omission].to_s  
  end   
end

app/helpers/equipo_helper.rb
module EquipoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/equipo/index.html.erb
<div class="row" id="portada-team">
    <div class="col-lg-12 col-xs-12 title">
        <p class="title">equipo</p>
    </div>
    <div class="col-lg-12 col-xs-12 foto">

    </div>
</div>

<div class="row" id="team">
    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-3 col-lg-offset-1 images">
                    <%= image_tag  'img_equipo-3.jpg' %>
                    <p class="title">José Lara</p>
                    <p class="light">
                        Lorem ipsum dolor sit cuchuflí barquillo bacán jote gamba listeilor po cahuín, luca melón con vino pichanga coscacho ni ahí peinar
                    </p>
                </div>
                <div class="col-lg-3 images">
                    <%= image_tag  'img_equipo-2.jpg' %>
                    <p class="title">Juan Soto</p>
                    <p class="light">
                        Lorem ipsum dolor sit cuchuflí barquillo bacán jote gamba listeilor po cahuín, luca melón con vino pichanga coscacho ni ahí peinar
                    </p>
                </div>
                <div class="col-lg-3 images">
                    <%= image_tag  'img_equipo-1.jpg' %>
                    <p class="title">María Osses</p>
                    <p class="light">
                        Lorem ipsum dolor sit cuchuflí barquillo bacán jote gamba listeilor po cahuín, luca melón con vino pichanga coscacho ni ahí peinar
                    </p>
                </div>
            </div>

             <div class="row">
                <div class="col-lg-3 col-lg-offset-1 images">
                    <%= image_tag  'img_equipo-3.jpg' %>
                    <p class="title">José Lara</p>
                    <p class="light">
                        Lorem ipsum dolor sit cuchuflí barquillo bacán jote gamba listeilor po cahuín, luca melón con vino pichanga coscacho ni ahí peinar
                    </p>
                </div>
                <div class="col-lg-3 images">
                    <%= image_tag  'img_equipo-2.jpg' %>
                    <p class="title">Juan Soto</p>
                    <p class="light">
                        Lorem ipsum dolor sit cuchuflí barquillo bacán jote gamba listeilor po cahuín, luca melón con vino pichanga coscacho ni ahí peinar
                    </p>
                </div>
                <div class="col-lg-3 images">
                    <%= image_tag  'img_equipo-1.jpg' %>
                    <p class="title">María Osses</p>
                    <p class="light">
                        Lorem ipsum dolor sit cuchuflí barquillo bacán jote gamba listeilor po cahuín, luca melón con vino pichanga coscacho ni ahí peinar
                    </p>
                </div>
            </div>

        </div>
    </div>

</div>

<div class="row" id="team_bottom">
    <div class="container">
        <div class="col-lg-12">
            <center>
                <a href="/"><%= image_tag 'btn_home.png' %></a>
            </center>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="row">
    <div class="col-lg-12 col-xs-12" id="portada">
        <div class="row">
            <% if(not @last_tip.nil?) %>
            <div class="visible-md visible-lg visible-sm hidden-xs" id="saludo">
                <p class="strong">ÚLTIMOS TIPS</p>
                <p class="light">
                   <%= truncate(strip_tags(@last_tip.texto),:length => 200,:omision => '...',:escape => false   ) %>

                </p>

                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-2 ">
                        <a href="<%= tip_url(@last_tip) %>" class="btn btn-mas">+Leer más</a>

                    </div>
                </div>

            </div>
            <% end %>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12 col-xs-12" id="who">
        <p class="title">QUIENES SOMOS</p>

        <div class="col-lg-10 col-lg-offset-1">
            <p class="light">
            Somos un equipo especializado en el tratamiento y rehabilitación de distintas lesiones, especialmente en articulaciones. Te entregamos un ambiente agradable, cercano y motivado para progresar juntos en tu recuperación.
            <br />
            <br />
            <em>"Las caídas solo nos enseñan a levantarnos"</em>
            </p>
        </div>
    </div>
</div>



<div class="row visible-lg" id="service_anchor">
    <div class="col-lg-12">
        <p class="title">SERVICIOS</p>

    </div>
    <div class="col-lg-12" id="servicios">
        <a href="/service/kine/">
            <div class="col-lg-4 background" id="kine">
                <div class="overlay">
                    <p class="title">Kinesiología</p>
                </div>
            </div>
        </a>
        <a href="/service/masaje/">
            <div class="col-lg-4 background" id="masaje">
                <div class="overlay">
                    <p class="title">Masajes</p>
                </div>
            </div>
        </a>
        <a href="/service/fisico/">
            <div class="col-lg-4 background" id="fisico">
                <div class="overlay">
                    <p class="title">actividad fisica y salud</p>
                </div>
            </div>
        </a>
    </div>
</div>



<div class="row">
    <div class="col-lg-12 col-xs-12" id="promociones">
        <p class="title">PROMOCIONES</p>
        <% if(not @promociones.nil?) %>
        <div class="carousel slide" id="carousel-promo" data-ride="carousel">
            <!-- Indicators -->
              <ol class="carousel-indicators">
                <% @promociones.each_with_index do |p,idx| %>
                    <% if (idx==0) %>
                        <li data-target="#carousel-promo" data-slide-to="0" class="active"></li>
                    <% else %>
                        <li data-target="#carousel-promo" data-slide-to="<%= idx%>"></li>
                    <% end %>
                <% end %>
              </ol>

              <div class="carousel-inner">
                <% @promociones.each_with_index do |p,idx| %>
                    <% if (idx==0) %>
                    <div class="item active">
                    <% else %>
                    <div class="item">
                    <% end %>
                        <div class="col-lg-3 col-lg-offset-2 col-sm-3 col-sm-offset-2">

                            <a href="/store">
                                <%= image_tag p.imagen.url(:small), size:"240x240" %>
                            </a>
                        </div>
                        <div class="col-lg-7 col-sm-6">
                            <div class="row">
                                <div class="col-lg-7">
                                    <p class="title light no-margin-bottom align-left">
                                        <a href="/store">
                                            <%= p.nombre %>
                                        </a>
                                    </p>
                                    <p class="title subtitle no-margin-top no-margin-bottom align-left"><%= p.descuento %>% descuento</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-10 content light no-margin-bottom">

                                    <%= truncate(raw(p.descripcion),:length => 300,:omision => '...',:escape => false   ) %>

                                </div>
                            </div>

                        </div>
                    </div>
                <% end %>

            </div>


        </div>
        <% end %>

    </div>
</div>


<div class="row">
    <div class="col-lg-12 col-xs-12" id="tips">
        <p class="title">ALGUNOS TIPS</p>
        <% @tips.each_slice(2) do |slice| %>
            <div class="row" id="first-tips">
            <% slice.each_with_index do |item,idx| %>
                <% if(idx==0) %>
                <div class="col-lg-5 col-lg-offset-1 col-md-6 visible-lg visible-md">
                <% else %>
                <div class="col-lg-5 col-md-6 col-xs-11 visible-lg visible-md">
                <% end %>
                    <div class="col-lg-12 col-md-6 col-md-offset-2 ">
                        <a href="<%= tip_url(item) %>">
                        <%= image_tag item.portada.url(:small), size:"200x200" %>
                        </a>
                    </div>
                    <article class="col-lg-12 col-md-11 col-md-offset-1">
                        <div class="row">
                            <p class="title tiny align-left no-margin-bottom">
                                <a href="<%= tip_url(item) %>">
                                <%= item.titulo %>
                                </a>
                            </p>
                        </div>
                        <div class="row">
                            <p class="light align-left no-margin-top">
                                <%= truncate(strip_tags(item.texto),:length => 250,:omision => '...',:escape => false) %>
                            </p>
                        </div>

                    </article>

                </div>

                <div class="visible-sm visible-xs col-sm-12 col-xs-12 mini-tips">
                    <center>
                    <div class="col-xs-12 col-sm-12">
                        <a href="<%= tip_url(item) %>">
                        <%= image_tag item.portada.url(:small), size:"200x200" %>
                        </a>
                    </div>
                    </center>
                    <article class="col-xs-12 col-sm-12">
                        <div class="row">
                            <p class="title tiny">
                                <a href="<%= tip_url(item) %>">
                                <%= item.titulo %>
                                </a>
                            </p>
                        </div>
                        <div class="row">
                            <p class="light no-margin-top">
                                <%= truncate(strip_tags(item.texto),:length => 250,:omision => '...',:escape => false) %>
                            </p>
                        </div>
                    </article>
                </div>

            <% end %>
            </div>
        <% end %>


        <div class="row">
            <div class="col-lg-2 col-lg-offset-5 col-md-3 col-md-offset-4 col-xs-12 col-sm-5">
                <a href="/tips" class="btn btn-mas pull-right">+LEER MÁS TIPS</a>
            </div>
        </div>

    </div>
</div>


<% cache do %>
<div class="row">
    <div class="col-lg-12 col-xs-12" id="contacto">
        <p class="title">CONTACTO</p>

        <div class="row">
            <div class="col-lg-4 col-lg-offset-2">
                <%= form_for @message do |f| %>
                    <div class="form-group">
                        <%= f.text_field :name, :class => 'form-control', :placeholder => 'Nombre' %>
                    </div>
                    <div class="form-group">
                        <%= f.text_field :email, :class => 'form-control', :placeholder => 'Email' %>
                    </div>
                    <div class="form-group">
                        <%= f.text_area :content, :class => 'form-control', :placeholder => 'Mensaje', :rows => 6 %>
                    </div>
                    <div style="display: none;visibility:hidden">
                        <%= f.text_field :nickname %>
                      </div>
                    <div class="form-group">
                        <button  type="submit" class="btn btn-mas">Enviar</button>
                    </div>
                <% end %>
            </div>
            <div class="col-lg-5">
                <div id="map-canvas"></div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/service/_portada.html.erb
<div class="row" id="portada-servicios">
    <div class="row visible-xs visible-sm nav-sm">
        <div class="col-xs-4 col-sm-4 align-right">
            <a href="/service/kine">KINESIOLOGÍA</a>
        </div>
        <div class="col-xs-4 col-sm-4 align-left">
            <a href="/service/masaje">MASAJES</a>
        </div>
        <div class="col-xs-4 col-sm-4 align-left">
            <a href="/service/fisico">ACTIVIDAD FÍSICA</a>
        </div>
    </div>
    <div class="col-lg-12 col-xs-12 title">
        <p class="title">Servicios</p>
    </div>
    
    <div class="col-lg-12 col-xs-12 foto">
        <div class="row">
            <div class="visible-md visible-lg hidden-sm hidden-xs" id="saludo">
                <ul>
                    <li id="kine"><a href="/service/kine/"> KINESIOLOGía</a></li>
                    <li id="masaje"><a href="/service/masaje/"> Masajes</a></li>
                    <li id="fisico"><a href="/service/fisico/"> actividad física</a></li>
                <ul>
            </div>
        </div>
    </div>
</div>

app/views/service/fisico.html.erb
<%= render "portada" %>
<% cache do %>
<div class="row">
    <div class="container">
        <div class="col-lg-12 col-xs-12" id="service-type">
            <p class="title">Servicios ofrecidos</p>


            <!-- <div class="col-lg-10 col-lg-offset-1">
                <p class="light">
                    Lorem ipsum dolor sit cuchuflí barquillo bacán jote gamba listeilor po cahuín, luca melón con vino pichanga coscacho ni ahí peinar la muñeca chuchada al chancho achoclonar. Chorrocientos pituto ubicatex huevo duro bolsero cachureo el hoyo del queque en cana huevón el año del loly hacerla corta
                </p>
            </div> -->
        </div>
    </div>
</div>

<div class="row">
    <div class="container">

        <div class="row service-images">
            <div class="col-lg-5 col-lg-offset-1 images">
                <%= image_tag 'fisico/entrenamiento.jpg',:class =>'img-responsive' %>
                <p class="title no-margin-bottom">Entrenamiento personalizado</p>
                <p class="subtitle">Mejora tu capacidad física bajo supervisión</p>
                <p class="light">
                    Entrena y mejora tu capacidad física realizando ejercicios preparados a tu medida bajo una supervisión directa y constante.
                </p>
            </div>
            <div class="col-lg-5 images">
                <%= image_tag 'fisico/evaluacion.JPG',:class =>'img-responsive' %>
                <p class="title no-margin-bottom">Evaluación física y de composición corporal</p>
                <p class="subtitle"></p>
                <p class="light">
                    Evaluamos tu condición física para generar un plan deportivo especializado a tus necesidades.
                </p>
            </div>
        </div>

        <div class="row service-images">
            <div class="col-lg-5 col-lg-offset-1 images">
                <%= image_tag 'fisico/riesgoscardio.jpg',:class =>'img-responsive' %>
                <p class="title no-margin-bottom">Prevención de riesgo cardiovasculares</p>
                <p class="subtitle">Hipertensión, diabetes, obesidad, sendentarismo...</p>
                <p class="light">
                    Ayudamos a la prevensión de riesgo cardiovascular gracias a nuestros planes de entrenamiento orientados a mejorar tu calidad de vida.
                </p>
            </div>
            <div class="col-lg-5 images">
                <%= image_tag 'fisico/post-trauma.jpg',:class =>'img-responsive' %>
                <p class="title no-margin-bottom">Deporte post trauma</p>
                <p class="subtitle">Para nuestros pacientes traumatológicos</p>
                <p class="light">
                    Entregamos un plan deportivo específico para retomar el deporte después de una lesión.
                </p>
            </div>
        </div>

        
    </div>

</div>


<div class="row visible-md visible-lg" id="service_bottom">
    <div class="container">
        <div class="col-lg-4 col-lg-offset-1 left">
            <p class="title">
                <a href="/service/masaje/">Masajes</a>
            </p>
        </div>
        <div class="col-lg-1 center">
            <center>
                <a href="/"><%= image_tag 'btn_home.png' %></a>
            </center>
        </div>
        <div class="col-lg-5 right">
            <p class="title ">
                <a href="/service/kine">Kinesiología</a>
            </p>
        </div>
    </div>
</div>
<% end %>

app/views/tips/index.html.erb
<div class="row" id="portada-tips">
    <div class="col-lg-12 col-xs-12 title">
        <p class="title">Tips y Consejos</p>
    </div>

</div>


<div class="row" id="tips-list">
    <div class="container">
        <div class="col-lg-12">
            <% @tips.each_slice(2) do |slice| %>
                <div class="row">
                <% slice.each_with_index do |item,idx| %>
                    <% if(idx == 0) %>
                    <div class="col-lg-5 col-lg-offset-1 images visible-lg visible-md">
                    <% else %>
                    <div class="col-lg-5 images visible-lg visible-md">
                    <% end %>
                        <div class="row">
                            <div class="col-lg-6">
                                <a href="<%= tip_url(item) %>">
                                    <%= image_tag item.portada.url(:small), size:"200x200", class:"left image-responsive" %>
                                </a>
                            </div>
                            <div class="col-lg-6">
                                <div class="col-lg-12 no-margin-bottom"><p class="day"><%= item.created_at.strftime('%d') %></p></div>
                                <div class="col-lg-12 no-margin-top"><p class="month"><%= item.created_at.strftime('%B') %></p></div>
                                <div class="col-lg-12">
                                    <a href="http://www.facebook.com/sharer.php?s=100&p[title]=<%=item.titulo%>&p[url]=<%=tip_url(item)%>&p[images][0]=<%="http://#{request.host}:#{request.port}#{item.portada.url(:large)}"%>" target="_blank">
                                        <div class="share fb"></div>
                                    </a>
                                    <a href="http://pinterest.com/pin/create/button/?url=<%= tip_url(item) %>&media=<%="http://#{request.host}:#{request.port}#{item.portada.url(:large)}"%>" target="_blank">
                                        <div class="share pn"></div>
                                    </a>
                                    <a href="https://twitter.com/share?url=<%=tip_url(item)%>&text=Nuevo en Viverelajacion: <%=item.titulo%>&hashtags=Viverelajacion"  target="_blank">
                                        <div class="share tw"></div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <p class="title">
                                <a href="<%= tip_url(item) %>"><%= item.titulo %></a>
                            </p>
                            <div class="light">
                                <%= raw(HTML_Truncator.truncate(item.texto, 20)) %>
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 visible-xs visible-sm mini-videos">
                        <center>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12">
                                <a href="<%= tip_url(item) %>">
                                    <%= image_tag item.portada.url(:small), size:"200x200", class:"left image-responsive" %>
                                </a>
                            </div>
                            <div class="col-xs-12 col-sm-12">
                                <div class="col-xs-6 col-sm-6 no-margin-bottom"><p class="day"><%= item.created_at.strftime('%d') %></p></div>
                                <div class="col-xs-6 col-sm-6 no-margin-top"><p class="month"><%= item.created_at.strftime('%B') %></p></div>
                                <div class="col-xs-12 col-sm-12">
                                    <a href="http://www.facebook.com/sharer.php?s=100&p[title]=<%=item.titulo%>&p[url]=<%=tip_url(item)%>&p[images][0]=<%="http://#{request.host}:#{request.port}#{item.portada.url(:large)}"%>" target="_blank">
                                        <div class="share fb"></div>
                                    </a>
                                    <a href="http://pinterest.com/pin/create/button/?url=<%= tip_url(item) %>&media=<%="http://#{request.host}:#{request.port}#{item.portada.url(:large)}"%>" target="_blank">
                                        <div class="share pn"></div>
                                    </a>
                                    <a href="https://twitter.com/share?url=<%=tip_url(item)%>&text=Nuevo en Viverelajacion: <%=item.titulo%>&hashtags=Viverelajacion"  target="_blank">
                                        <div class="share tw"></div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <p class="title">
                                <a href="<%= tip_url(item) %>"><%= item.titulo %></a>
                            </p>
                            <div class="light">
                                <%= raw(HTML_Truncator.truncate(item.texto, 20)) %>
                            </div>
                        </div>
                        </center>
                    </div>
                <% end -%>
                </div>
            <% end -%>



        </div>
    </div>

</div>




<div class="row" id="team_bottom">
    <div class="container">
        <div class="col-lg-12">
            <center>
                <a href="/"><%= image_tag 'btn_home.png' %></a>
            </center>
        </div>
    </div>

</div>

app/views/tips/show.html.erb
<div class="row" id="portada-tips">
    <div class="col-lg-12 col-xs-12 title">
        <p class="title">Tips y Consejos</p>
    </div>

</div>


<div class="row" id="tip">

    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="date"><%= @tip.created_at.strftime('%d de %B %Y') %></p>
                <p class="title">
                    <%= @tip.titulo %>
                </p>
                <%= image_tag @tip.portada.url(:large),size: @tip.portada.image_size(:large),:class => 'img-responsive' %>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-5 col-lg-offset-1">

                <a href="http://www.facebook.com/sharer.php?s=100&p[title]=<%=@tip.titulo%>&p[url]=<%=tip_url(@tip)%>&p[images][0]=<%=@image%>" target="_blank">
                    <div class="share fb"></div>
                </a>
                <a href="http://pinterest.com/pin/create/button/?url=<%= tip_url(@tip) %>&media=<%=@image%>" target="_blank">
                    <div class="share pn"></div>
                </a>
                <a href="https://twitter.com/share?url=<%=tip_url(@tip)%>&text=Nuevo en Viverelajacion: <%=@tip.titulo%>&hashtags=Viverelajacion"  target="_blank">
                    <div class="share tw"></div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <p class="author">por Administrador</p>
                <div class="contenido">
                    <%= raw(@tip.texto) %>
                </div>
            </div>
        </div>
    </div>
</div>




<div class="row" id="team_bottom">

    <div class="col-lg-12">
        <center>
            <a href="/"><%= image_tag 'btn_home.png' %></a>
        </center>
    </div>

</div>